---
- name: Analysis
  hosts: localhost
  gather_facts: true
  become: true
  force_handlers: true

  tasks:
    - name: Generate pre-conversion analysis report
      ansible.builtin.import_role:
        name: ../roles/analysis
...
